INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, MOBILE_NUMBER, CITY, CUSTOMER_STATUS)
SELECT
    LEVEL,
    'Customer_' || LEVEL,
    '9' || LPAD(TRUNC(DBMS_RANDOM.VALUE(100000000,999999999)),9,'0'),
    CASE MOD(LEVEL,4)
        WHEN 0 THEN 'Erode'
        WHEN 1 THEN 'Salem'
        WHEN 2 THEN 'Chennai'
        ELSE 'Coimbatore'
    END,
    'ACTIVE'
FROM DUAL
CONNECT BY LEVEL <= 300;
INSERT INTO RESTAURANT (RESTAURANT_ID, RESTAURANT_NAME, CUISINE_TYPE, CITY, RESTAURANT_STATUS)
SELECT
    1000 + LEVEL,
    'Restaurant_' || LEVEL,
    CASE MOD(LEVEL,3)
        WHEN 0 THEN 'South Indian'
        WHEN 1 THEN 'Chinese'
        ELSE 'North Indian'
    END,
    CASE MOD(LEVEL,3)
        WHEN 0 THEN 'Erode'
        WHEN 1 THEN 'Salem'
        ELSE 'Chennai'
    END,
    CASE WHEN MOD(LEVEL,10)=0 THEN 'CLOSED' ELSE 'OPEN' END
FROM DUAL
CONNECT BY LEVEL <= 50;
INSERT INTO FOOD_ORDER (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_AMOUNT, ORDER_STATUS)
SELECT
    10000 + LEVEL,
    TRUNC(DBMS_RANDOM.VALUE(1,300)),
    1000 + TRUNC(DBMS_RANDOM.VALUE(1,50)),
    TRUNC(DBMS_RANDOM.VALUE(50,1000)),
    CASE MOD(LEVEL,4)
        WHEN 0 THEN 'DELIVERED'
        WHEN 1 THEN 'CANCELLED'
        WHEN 2 THEN 'PENDING'
        ELSE 'DELIVERED'
    END
FROM DUAL
CONNECT BY LEVEL <= 300;
INSERT INTO DELIVERY_TRANSACTION (DELIVERY_ID, ORDER_ID, DELIVERY_PARTNER, DELIVERY_DATE, DELIVERY_STATUS)
SELECT
    50000 + LEVEL,
    10000 + LEVEL,
    CASE MOD(LEVEL,3)
        WHEN 0 THEN 'Swiggy'
        WHEN 1 THEN 'Zomato'
        ELSE 'Blinkit'
    END,
    SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,10)),
    CASE MOD(LEVEL,3)
        WHEN 0 THEN 'DELIVERED'
        WHEN 1 THEN 'FAILED'
        ELSE 'DELIVERED'
    END
FROM DUAL
CONNECT BY LEVEL <= 300;